name: my_login_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.8.1

flutter_native_splash:
  color: "#f7f6ff"
  color_dark: "#272727"
  image: assets/images/splash_logo.png
  image_dark: assets/images/splash_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  line_awesome_flutter: ^3.0.1
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.6
  get: ^4.7.2
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.2.1
  flutter_otp_text_field: ^1.5.1+1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/images/splash_logo.png
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/welcome_screen/
